import Navbar from "@/components/navbar";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Sidebar from "@/components/sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "PICTURE GALLERY",
  description: "Generated by SHAHZAIB",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="dark">
      <body className={inter.className}>
        <Navbar />
        <div className="flex flex-col lg:flex-row">
          <div className="flex">
            <div className="w-1/5">
              <Sidebar />
            </div>
            <div className="w-full">{children}</div>
          </div>
        </div>
      </body>
    </html>
  );
}
